### ISSUE TITLE
Triton version?

### ISSUE THREAD

**Issue by hezhengting** [Xuan-World/Mamba-YOLO-World#4]
I tried to run the image_demo as below
python demo/image_demo.py --config configs/mamba2_yolo_world_s.py  --checkpoint MambaYOLOWorld_s_pretrain_O365GoldG.pth  --image my_image.jpg  --text food

and I got error below. The triton version is not correct?
Traceback (most recent call last):
  File "/mnt/d/dev/mamba_yolo_world/Mamba-YOLO-World/demo/image_demo.py", line 185, in <module>
    cfg = Config.fromfile(args.config)
  File "/mnt/d/pyvenv_wsl/dinov2/lib/python3.9/site-packages/mmengine/config/config.py", line 462, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/mnt/d/pyvenv_wsl/dinov2/lib/python3.9/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/mnt/d/pyvenv_wsl/dinov2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/d/dev/mamba_yolo_world/Mamba-YOLO-World/yolo_world/__init__.py", line 10, in <module>
    from .models import *  # noqa
  File "/mnt/d/dev/mamba_yolo_world/Mamba-YOLO-World/yolo_world/models/__init__.py", line 3, in <module>
    from .layers import *  # noqa
  File "/mnt/d/dev/mamba_yolo_world/Mamba-YOLO-World/yolo_world/models/layers/__init__.py", line 12, in <module>
    from .mamba2_yolo_bricks import (
  File "/mnt/d/dev/mamba_yolo_world/Mamba-YOLO-World/yolo_world/models/layers/mamba2_yolo_bricks.py", line 15, in <module>
    from .VMamba.models.csm_triton2 import cross_scan_fn, cross_merge_fn
  File "/mnt/d/dev/mamba_yolo_world/Mamba-YOLO-World/yolo_world/models/layers/VMamba/models/csm_triton2.py", line 279, in <module>
    def triton_cross_scan_flex(
  File "/mnt/d/pyvenv_wsl/dinov2/lib/python3.9/site-packages/triton/runtime/jit.py", line 419, in jit
    return decorator(fn)
  File "/mnt/d/pyvenv_wsl/dinov2/lib/python3.9/site-packages/triton/runtime/jit.py", line 412, in decorator
    return JITFunction(
  File "/mnt/d/pyvenv_wsl/dinov2/lib/python3.9/site-packages/triton/runtime/jit.py", line 321, in __init__
    self.run = self._make_launcher()
  File "/mnt/d/pyvenv_wsl/dinov2/lib/python3.9/site-packages/triton/runtime/jit.py", line 291, in _make_launcher
    exec(src, scope)
  File "<string>", line 3
    sig_key =  ,

**Comment by Xuan-World** [comment]
**triton==2.1.0**  Thanks for reminding me, the version has been declared in **readme.md**.
